name: ad_bs_calendar_example
description: Demonstrates how to use the ad_bs_calendar plugin.
publish_to: 'none'

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  ad_bs_calendar:
    path: ../


flutter:

  uses-material-design: true
